### Login
POST centsapi.com.test/api/login HTTP/1.1
Content-type: application/json
Accept: application/json

{
    "email": "admin@cents.test",
    "password": "password"
}

#### LISTAS

### Listar Listas
GET centsapi.com.test/api/listas HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTdiMmNkZWFjOGJiNzc4ZjAwMTMxMzRmMGRkMDI0MTk5ZDYxMzcwYjZiYjA4MGQ5YTRiYmNkOGNmYjAzMjgzYjU0NGQ2ZTdhYjNlYTE5MGYiLCJpYXQiOjE2MDU4MjI5OTAsIm5iZiI6MTYwNTgyMjk5MCwiZXhwIjoxNjM3MzU4OTkwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.xZLnlo1kOHLvdC_HAu6zU4REfIoVeeLEXgCJebsTYsHMvOZsoCVKAaYADCh5J__iZyZaak3zLdBz-2EYb53XeAjzQwzE-D8uKBCMwvCAxvV6qKxhEhv6lRU-To9XlSQSOtXWGCpRhy0qTADjrlS06yVBynYxC-a-7b5DJmDqB4hIuhZKOoFouomQLs2CSH15AGlDx7GFjK4ZOtzAl1AxiRhYKFr0DN1uKExFZHPMmckT5SpR4QkhBcvK10XlxAqccJoAFW9v1bGVuiUhoNjLMUnwdIf336MmN3Vgt_SwjGfOxvR8EBvKP0BznoIrCsom7MCeTxw8frdCIDEQJy5_5cTr_fiLPA7hJX32Vv8XNOgRGpwYaky8_7j_kEt_7dcHGH0fpZXkLFO90ZiZk95G5P_nzGWl5r93S_NpLVG9BVIhEwTiFTi_hFRv_UiEPf7PaxnIB67oF8CtIhE8j2ILsXARgMpfRB6bq9fkNc_TzMA2QzBzmNDNnuohNeJUtC3HCJv6ctH0UjiyJ01FLcatMReWftNyS7TXH7_DQyUpF9Cz1r49wb9qFImzzBpIxEp98gX0DfW_RgWERfUFHhGVWPmFgZOVsgt33NS3zhJqJQT31AcXMmZaCj1TiGFF2zvcaaOomM3-9YeXqKr1i0s6xiau1DcXjs1Sbg_MA-HJYWI
Content-type: application/json
Accept: application/json

### Criar Lista
POST centsapi.com.test/api/listas HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTdiMmNkZWFjOGJiNzc4ZjAwMTMxMzRmMGRkMDI0MTk5ZDYxMzcwYjZiYjA4MGQ5YTRiYmNkOGNmYjAzMjgzYjU0NGQ2ZTdhYjNlYTE5MGYiLCJpYXQiOjE2MDU4MjI5OTAsIm5iZiI6MTYwNTgyMjk5MCwiZXhwIjoxNjM3MzU4OTkwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.xZLnlo1kOHLvdC_HAu6zU4REfIoVeeLEXgCJebsTYsHMvOZsoCVKAaYADCh5J__iZyZaak3zLdBz-2EYb53XeAjzQwzE-D8uKBCMwvCAxvV6qKxhEhv6lRU-To9XlSQSOtXWGCpRhy0qTADjrlS06yVBynYxC-a-7b5DJmDqB4hIuhZKOoFouomQLs2CSH15AGlDx7GFjK4ZOtzAl1AxiRhYKFr0DN1uKExFZHPMmckT5SpR4QkhBcvK10XlxAqccJoAFW9v1bGVuiUhoNjLMUnwdIf336MmN3Vgt_SwjGfOxvR8EBvKP0BznoIrCsom7MCeTxw8frdCIDEQJy5_5cTr_fiLPA7hJX32Vv8XNOgRGpwYaky8_7j_kEt_7dcHGH0fpZXkLFO90ZiZk95G5P_nzGWl5r93S_NpLVG9BVIhEwTiFTi_hFRv_UiEPf7PaxnIB67oF8CtIhE8j2ILsXARgMpfRB6bq9fkNc_TzMA2QzBzmNDNnuohNeJUtC3HCJv6ctH0UjiyJ01FLcatMReWftNyS7TXH7_DQyUpF9Cz1r49wb9qFImzzBpIxEp98gX0DfW_RgWERfUFHhGVWPmFgZOVsgt33NS3zhJqJQT31AcXMmZaCj1TiGFF2zvcaaOomM3-9YeXqKr1i0s6xiau1DcXjs1Sbg_MA-HJYWI
Content-type: application/json
Accept: application/json

{
    "title": "teste criando."
}

### Alterar Lista
PUT centsapi.com.test/api/listas/9 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTdiMmNkZWFjOGJiNzc4ZjAwMTMxMzRmMGRkMDI0MTk5ZDYxMzcwYjZiYjA4MGQ5YTRiYmNkOGNmYjAzMjgzYjU0NGQ2ZTdhYjNlYTE5MGYiLCJpYXQiOjE2MDU4MjI5OTAsIm5iZiI6MTYwNTgyMjk5MCwiZXhwIjoxNjM3MzU4OTkwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.xZLnlo1kOHLvdC_HAu6zU4REfIoVeeLEXgCJebsTYsHMvOZsoCVKAaYADCh5J__iZyZaak3zLdBz-2EYb53XeAjzQwzE-D8uKBCMwvCAxvV6qKxhEhv6lRU-To9XlSQSOtXWGCpRhy0qTADjrlS06yVBynYxC-a-7b5DJmDqB4hIuhZKOoFouomQLs2CSH15AGlDx7GFjK4ZOtzAl1AxiRhYKFr0DN1uKExFZHPMmckT5SpR4QkhBcvK10XlxAqccJoAFW9v1bGVuiUhoNjLMUnwdIf336MmN3Vgt_SwjGfOxvR8EBvKP0BznoIrCsom7MCeTxw8frdCIDEQJy5_5cTr_fiLPA7hJX32Vv8XNOgRGpwYaky8_7j_kEt_7dcHGH0fpZXkLFO90ZiZk95G5P_nzGWl5r93S_NpLVG9BVIhEwTiFTi_hFRv_UiEPf7PaxnIB67oF8CtIhE8j2ILsXARgMpfRB6bq9fkNc_TzMA2QzBzmNDNnuohNeJUtC3HCJv6ctH0UjiyJ01FLcatMReWftNyS7TXH7_DQyUpF9Cz1r49wb9qFImzzBpIxEp98gX0DfW_RgWERfUFHhGVWPmFgZOVsgt33NS3zhJqJQT31AcXMmZaCj1TiGFF2zvcaaOomM3-9YeXqKr1i0s6xiau1DcXjs1Sbg_MA-HJYWI
Content-type: application/json
Accept: application/json

{
    "title": "renomeando lista."
}

### Remover Lista
DELETE centsapi.com.test/api/listas/7 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTdiMmNkZWFjOGJiNzc4ZjAwMTMxMzRmMGRkMDI0MTk5ZDYxMzcwYjZiYjA4MGQ5YTRiYmNkOGNmYjAzMjgzYjU0NGQ2ZTdhYjNlYTE5MGYiLCJpYXQiOjE2MDU4MjI5OTAsIm5iZiI6MTYwNTgyMjk5MCwiZXhwIjoxNjM3MzU4OTkwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.xZLnlo1kOHLvdC_HAu6zU4REfIoVeeLEXgCJebsTYsHMvOZsoCVKAaYADCh5J__iZyZaak3zLdBz-2EYb53XeAjzQwzE-D8uKBCMwvCAxvV6qKxhEhv6lRU-To9XlSQSOtXWGCpRhy0qTADjrlS06yVBynYxC-a-7b5DJmDqB4hIuhZKOoFouomQLs2CSH15AGlDx7GFjK4ZOtzAl1AxiRhYKFr0DN1uKExFZHPMmckT5SpR4QkhBcvK10XlxAqccJoAFW9v1bGVuiUhoNjLMUnwdIf336MmN3Vgt_SwjGfOxvR8EBvKP0BznoIrCsom7MCeTxw8frdCIDEQJy5_5cTr_fiLPA7hJX32Vv8XNOgRGpwYaky8_7j_kEt_7dcHGH0fpZXkLFO90ZiZk95G5P_nzGWl5r93S_NpLVG9BVIhEwTiFTi_hFRv_UiEPf7PaxnIB67oF8CtIhE8j2ILsXARgMpfRB6bq9fkNc_TzMA2QzBzmNDNnuohNeJUtC3HCJv6ctH0UjiyJ01FLcatMReWftNyS7TXH7_DQyUpF9Cz1r49wb9qFImzzBpIxEp98gX0DfW_RgWERfUFHhGVWPmFgZOVsgt33NS3zhJqJQT31AcXMmZaCj1TiGFF2zvcaaOomM3-9YeXqKr1i0s6xiau1DcXjs1Sbg_MA-HJYWI
Content-type: application/json
Accept: application/json

#### PRODUTOS

### Listar Produtos de uma lista
GET centsapi.com.test/api/listas/1/products HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTdiMmNkZWFjOGJiNzc4ZjAwMTMxMzRmMGRkMDI0MTk5ZDYxMzcwYjZiYjA4MGQ5YTRiYmNkOGNmYjAzMjgzYjU0NGQ2ZTdhYjNlYTE5MGYiLCJpYXQiOjE2MDU4MjI5OTAsIm5iZiI6MTYwNTgyMjk5MCwiZXhwIjoxNjM3MzU4OTkwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.xZLnlo1kOHLvdC_HAu6zU4REfIoVeeLEXgCJebsTYsHMvOZsoCVKAaYADCh5J__iZyZaak3zLdBz-2EYb53XeAjzQwzE-D8uKBCMwvCAxvV6qKxhEhv6lRU-To9XlSQSOtXWGCpRhy0qTADjrlS06yVBynYxC-a-7b5DJmDqB4hIuhZKOoFouomQLs2CSH15AGlDx7GFjK4ZOtzAl1AxiRhYKFr0DN1uKExFZHPMmckT5SpR4QkhBcvK10XlxAqccJoAFW9v1bGVuiUhoNjLMUnwdIf336MmN3Vgt_SwjGfOxvR8EBvKP0BznoIrCsom7MCeTxw8frdCIDEQJy5_5cTr_fiLPA7hJX32Vv8XNOgRGpwYaky8_7j_kEt_7dcHGH0fpZXkLFO90ZiZk95G5P_nzGWl5r93S_NpLVG9BVIhEwTiFTi_hFRv_UiEPf7PaxnIB67oF8CtIhE8j2ILsXARgMpfRB6bq9fkNc_TzMA2QzBzmNDNnuohNeJUtC3HCJv6ctH0UjiyJ01FLcatMReWftNyS7TXH7_DQyUpF9Cz1r49wb9qFImzzBpIxEp98gX0DfW_RgWERfUFHhGVWPmFgZOVsgt33NS3zhJqJQT31AcXMmZaCj1TiGFF2zvcaaOomM3-9YeXqKr1i0s6xiau1DcXjs1Sbg_MA-HJYWI
Content-type: application/json
Accept: application/json

### Criar Produto em uma lista
POST centsapi.com.test/api/listas/1/products HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTdiMmNkZWFjOGJiNzc4ZjAwMTMxMzRmMGRkMDI0MTk5ZDYxMzcwYjZiYjA4MGQ5YTRiYmNkOGNmYjAzMjgzYjU0NGQ2ZTdhYjNlYTE5MGYiLCJpYXQiOjE2MDU4MjI5OTAsIm5iZiI6MTYwNTgyMjk5MCwiZXhwIjoxNjM3MzU4OTkwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.xZLnlo1kOHLvdC_HAu6zU4REfIoVeeLEXgCJebsTYsHMvOZsoCVKAaYADCh5J__iZyZaak3zLdBz-2EYb53XeAjzQwzE-D8uKBCMwvCAxvV6qKxhEhv6lRU-To9XlSQSOtXWGCpRhy0qTADjrlS06yVBynYxC-a-7b5DJmDqB4hIuhZKOoFouomQLs2CSH15AGlDx7GFjK4ZOtzAl1AxiRhYKFr0DN1uKExFZHPMmckT5SpR4QkhBcvK10XlxAqccJoAFW9v1bGVuiUhoNjLMUnwdIf336MmN3Vgt_SwjGfOxvR8EBvKP0BznoIrCsom7MCeTxw8frdCIDEQJy5_5cTr_fiLPA7hJX32Vv8XNOgRGpwYaky8_7j_kEt_7dcHGH0fpZXkLFO90ZiZk95G5P_nzGWl5r93S_NpLVG9BVIhEwTiFTi_hFRv_UiEPf7PaxnIB67oF8CtIhE8j2ILsXARgMpfRB6bq9fkNc_TzMA2QzBzmNDNnuohNeJUtC3HCJv6ctH0UjiyJ01FLcatMReWftNyS7TXH7_DQyUpF9Cz1r49wb9qFImzzBpIxEp98gX0DfW_RgWERfUFHhGVWPmFgZOVsgt33NS3zhJqJQT31AcXMmZaCj1TiGFF2zvcaaOomM3-9YeXqKr1i0s6xiau1DcXjs1Sbg_MA-HJYWI
Content-type: application/json
Accept: application/json

{
    "title": "produto criando.",
    "quantity": 2,
    "value": 10.20
}

### Alterar Produto em uma lista
PUT centsapi.com.test/api/listas/1/products/32 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTdiMmNkZWFjOGJiNzc4ZjAwMTMxMzRmMGRkMDI0MTk5ZDYxMzcwYjZiYjA4MGQ5YTRiYmNkOGNmYjAzMjgzYjU0NGQ2ZTdhYjNlYTE5MGYiLCJpYXQiOjE2MDU4MjI5OTAsIm5iZiI6MTYwNTgyMjk5MCwiZXhwIjoxNjM3MzU4OTkwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.xZLnlo1kOHLvdC_HAu6zU4REfIoVeeLEXgCJebsTYsHMvOZsoCVKAaYADCh5J__iZyZaak3zLdBz-2EYb53XeAjzQwzE-D8uKBCMwvCAxvV6qKxhEhv6lRU-To9XlSQSOtXWGCpRhy0qTADjrlS06yVBynYxC-a-7b5DJmDqB4hIuhZKOoFouomQLs2CSH15AGlDx7GFjK4ZOtzAl1AxiRhYKFr0DN1uKExFZHPMmckT5SpR4QkhBcvK10XlxAqccJoAFW9v1bGVuiUhoNjLMUnwdIf336MmN3Vgt_SwjGfOxvR8EBvKP0BznoIrCsom7MCeTxw8frdCIDEQJy5_5cTr_fiLPA7hJX32Vv8XNOgRGpwYaky8_7j_kEt_7dcHGH0fpZXkLFO90ZiZk95G5P_nzGWl5r93S_NpLVG9BVIhEwTiFTi_hFRv_UiEPf7PaxnIB67oF8CtIhE8j2ILsXARgMpfRB6bq9fkNc_TzMA2QzBzmNDNnuohNeJUtC3HCJv6ctH0UjiyJ01FLcatMReWftNyS7TXH7_DQyUpF9Cz1r49wb9qFImzzBpIxEp98gX0DfW_RgWERfUFHhGVWPmFgZOVsgt33NS3zhJqJQT31AcXMmZaCj1TiGFF2zvcaaOomM3-9YeXqKr1i0s6xiau1DcXjs1Sbg_MA-HJYWI
Content-type: application/json
Accept: application/json

{
    "title": "produto renomeado.",
    "quantity": 3,
    "value": 10.30
}

### Remover Produto em uma lista
DELETE centsapi.com.test/api/listas/31 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNTdiMmNkZWFjOGJiNzc4ZjAwMTMxMzRmMGRkMDI0MTk5ZDYxMzcwYjZiYjA4MGQ5YTRiYmNkOGNmYjAzMjgzYjU0NGQ2ZTdhYjNlYTE5MGYiLCJpYXQiOjE2MDU4MjI5OTAsIm5iZiI6MTYwNTgyMjk5MCwiZXhwIjoxNjM3MzU4OTkwLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.xZLnlo1kOHLvdC_HAu6zU4REfIoVeeLEXgCJebsTYsHMvOZsoCVKAaYADCh5J__iZyZaak3zLdBz-2EYb53XeAjzQwzE-D8uKBCMwvCAxvV6qKxhEhv6lRU-To9XlSQSOtXWGCpRhy0qTADjrlS06yVBynYxC-a-7b5DJmDqB4hIuhZKOoFouomQLs2CSH15AGlDx7GFjK4ZOtzAl1AxiRhYKFr0DN1uKExFZHPMmckT5SpR4QkhBcvK10XlxAqccJoAFW9v1bGVuiUhoNjLMUnwdIf336MmN3Vgt_SwjGfOxvR8EBvKP0BznoIrCsom7MCeTxw8frdCIDEQJy5_5cTr_fiLPA7hJX32Vv8XNOgRGpwYaky8_7j_kEt_7dcHGH0fpZXkLFO90ZiZk95G5P_nzGWl5r93S_NpLVG9BVIhEwTiFTi_hFRv_UiEPf7PaxnIB67oF8CtIhE8j2ILsXARgMpfRB6bq9fkNc_TzMA2QzBzmNDNnuohNeJUtC3HCJv6ctH0UjiyJ01FLcatMReWftNyS7TXH7_DQyUpF9Cz1r49wb9qFImzzBpIxEp98gX0DfW_RgWERfUFHhGVWPmFgZOVsgt33NS3zhJqJQT31AcXMmZaCj1TiGFF2zvcaaOomM3-9YeXqKr1i0s6xiau1DcXjs1Sbg_MA-HJYWI
Content-type: application/json
Accept: application/json
