### Login
POST http://phplaravel-299923-1600849.cloudwaysapps.com/api/login HTTP/1.1
Content-type: application/json
Accept: application/json

{
    "email": "admin@cents.test",
    "password": "password"
}

#### LISTAS

### Listar Listas
GET http://phplaravel-299923-1600849.cloudwaysapps.com/api/listas HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDc2YTZlYmVkZjYyZDJjNzkxNTExOTYzNDYyNmNkNjZiMmYzYWJjYzc0YThhNjIxNGYxNzdhMjhiYWEyY2EyN2VhNzQ1NGMzZTc1MjIxMjYiLCJpYXQiOjE2MDU4Mjg4MTgsIm5iZiI6MTYwNTgyODgxOCwiZXhwIjoxNjM3MzY0ODE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.S5k70sTEgt2RANiBTjRNm8_MZ0L7bu03jcqdqufmo_bJeLSCVakRvDnON3lYzCzD4pMCpiYShLh4ZPwPI2-r-7rt02_ntBJsFfpeJlhn9E_d6Mp0Nkfu9ap1WKOfIXpwa6b94geFTtqX-Kp4ZcEXwnrn1Kq0o287aixodR-Qfl5-BfzSflJrbUMMqRHIiBgef4drk8_8jZnu0CfNDcSYFGoUgjIYnKVlO8IzmSIgnXVgCETy5-WXhCQcmobjq8Pb2hJWcj8s6dOvawqygamIjOMB3k4w8-pMNhwtOfnJQTMJ2WDAMp-Vwyq-7rmnrDMnQ6c32XKOf5_8C_xXpPvcQ2oyasw6X-OcLw815XlAylMR2lbrTHEDUrvkxyGtiE87SzeKhaV0THj_PuRJt-wlgnmxkH5hi70fSApGqUSZoDbsCXTVD0tJRvsRH7WGbeKKuCQ6SC2RIVs5lUWu3euA2-qQlmB-iBmrVIFj4pNOFCzY-SswqlH7am0PaynDFIhNJTIap1yhF_LpBqNtQbT3yWBs55nlNLGd3nQlDBh5giCGXpAKhCNO4cpfLghmAk7Iarjkii0LBUmebTZF84w9MXGtOsn-9eyS9HiUIryhSB-X-XDdkPxHoRhjNmwRBX-rwWacgpEumMU_5NwAdsGQpRf0YAx8Tls7SY-a-_56Eo4
Content-type: application/json
Accept: application/json

### Criar Lista
POST http://phplaravel-299923-1600849.cloudwaysapps.com/api/listas HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDc2YTZlYmVkZjYyZDJjNzkxNTExOTYzNDYyNmNkNjZiMmYzYWJjYzc0YThhNjIxNGYxNzdhMjhiYWEyY2EyN2VhNzQ1NGMzZTc1MjIxMjYiLCJpYXQiOjE2MDU4Mjg4MTgsIm5iZiI6MTYwNTgyODgxOCwiZXhwIjoxNjM3MzY0ODE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.S5k70sTEgt2RANiBTjRNm8_MZ0L7bu03jcqdqufmo_bJeLSCVakRvDnON3lYzCzD4pMCpiYShLh4ZPwPI2-r-7rt02_ntBJsFfpeJlhn9E_d6Mp0Nkfu9ap1WKOfIXpwa6b94geFTtqX-Kp4ZcEXwnrn1Kq0o287aixodR-Qfl5-BfzSflJrbUMMqRHIiBgef4drk8_8jZnu0CfNDcSYFGoUgjIYnKVlO8IzmSIgnXVgCETy5-WXhCQcmobjq8Pb2hJWcj8s6dOvawqygamIjOMB3k4w8-pMNhwtOfnJQTMJ2WDAMp-Vwyq-7rmnrDMnQ6c32XKOf5_8C_xXpPvcQ2oyasw6X-OcLw815XlAylMR2lbrTHEDUrvkxyGtiE87SzeKhaV0THj_PuRJt-wlgnmxkH5hi70fSApGqUSZoDbsCXTVD0tJRvsRH7WGbeKKuCQ6SC2RIVs5lUWu3euA2-qQlmB-iBmrVIFj4pNOFCzY-SswqlH7am0PaynDFIhNJTIap1yhF_LpBqNtQbT3yWBs55nlNLGd3nQlDBh5giCGXpAKhCNO4cpfLghmAk7Iarjkii0LBUmebTZF84w9MXGtOsn-9eyS9HiUIryhSB-X-XDdkPxHoRhjNmwRBX-rwWacgpEumMU_5NwAdsGQpRf0YAx8Tls7SY-a-_56Eo4
Content-type: application/json
Accept: application/json

{
    "title": "teste criando."
}

### Alterar Lista
PUT http://phplaravel-299923-1600849.cloudwaysapps.com/api/listas/8 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDc2YTZlYmVkZjYyZDJjNzkxNTExOTYzNDYyNmNkNjZiMmYzYWJjYzc0YThhNjIxNGYxNzdhMjhiYWEyY2EyN2VhNzQ1NGMzZTc1MjIxMjYiLCJpYXQiOjE2MDU4Mjg4MTgsIm5iZiI6MTYwNTgyODgxOCwiZXhwIjoxNjM3MzY0ODE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.S5k70sTEgt2RANiBTjRNm8_MZ0L7bu03jcqdqufmo_bJeLSCVakRvDnON3lYzCzD4pMCpiYShLh4ZPwPI2-r-7rt02_ntBJsFfpeJlhn9E_d6Mp0Nkfu9ap1WKOfIXpwa6b94geFTtqX-Kp4ZcEXwnrn1Kq0o287aixodR-Qfl5-BfzSflJrbUMMqRHIiBgef4drk8_8jZnu0CfNDcSYFGoUgjIYnKVlO8IzmSIgnXVgCETy5-WXhCQcmobjq8Pb2hJWcj8s6dOvawqygamIjOMB3k4w8-pMNhwtOfnJQTMJ2WDAMp-Vwyq-7rmnrDMnQ6c32XKOf5_8C_xXpPvcQ2oyasw6X-OcLw815XlAylMR2lbrTHEDUrvkxyGtiE87SzeKhaV0THj_PuRJt-wlgnmxkH5hi70fSApGqUSZoDbsCXTVD0tJRvsRH7WGbeKKuCQ6SC2RIVs5lUWu3euA2-qQlmB-iBmrVIFj4pNOFCzY-SswqlH7am0PaynDFIhNJTIap1yhF_LpBqNtQbT3yWBs55nlNLGd3nQlDBh5giCGXpAKhCNO4cpfLghmAk7Iarjkii0LBUmebTZF84w9MXGtOsn-9eyS9HiUIryhSB-X-XDdkPxHoRhjNmwRBX-rwWacgpEumMU_5NwAdsGQpRf0YAx8Tls7SY-a-_56Eo4
Content-type: application/json
Accept: application/json

{
    "title": "renomeando lista."
}

### Remover Lista
DELETE http://phplaravel-299923-1600849.cloudwaysapps.com/api/listas/8 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDc2YTZlYmVkZjYyZDJjNzkxNTExOTYzNDYyNmNkNjZiMmYzYWJjYzc0YThhNjIxNGYxNzdhMjhiYWEyY2EyN2VhNzQ1NGMzZTc1MjIxMjYiLCJpYXQiOjE2MDU4Mjg4MTgsIm5iZiI6MTYwNTgyODgxOCwiZXhwIjoxNjM3MzY0ODE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.S5k70sTEgt2RANiBTjRNm8_MZ0L7bu03jcqdqufmo_bJeLSCVakRvDnON3lYzCzD4pMCpiYShLh4ZPwPI2-r-7rt02_ntBJsFfpeJlhn9E_d6Mp0Nkfu9ap1WKOfIXpwa6b94geFTtqX-Kp4ZcEXwnrn1Kq0o287aixodR-Qfl5-BfzSflJrbUMMqRHIiBgef4drk8_8jZnu0CfNDcSYFGoUgjIYnKVlO8IzmSIgnXVgCETy5-WXhCQcmobjq8Pb2hJWcj8s6dOvawqygamIjOMB3k4w8-pMNhwtOfnJQTMJ2WDAMp-Vwyq-7rmnrDMnQ6c32XKOf5_8C_xXpPvcQ2oyasw6X-OcLw815XlAylMR2lbrTHEDUrvkxyGtiE87SzeKhaV0THj_PuRJt-wlgnmxkH5hi70fSApGqUSZoDbsCXTVD0tJRvsRH7WGbeKKuCQ6SC2RIVs5lUWu3euA2-qQlmB-iBmrVIFj4pNOFCzY-SswqlH7am0PaynDFIhNJTIap1yhF_LpBqNtQbT3yWBs55nlNLGd3nQlDBh5giCGXpAKhCNO4cpfLghmAk7Iarjkii0LBUmebTZF84w9MXGtOsn-9eyS9HiUIryhSB-X-XDdkPxHoRhjNmwRBX-rwWacgpEumMU_5NwAdsGQpRf0YAx8Tls7SY-a-_56Eo4
Content-type: application/json
Accept: application/json

#### PRODUTOS

### Listar Produtos de uma lista
GET http://phplaravel-299923-1600849.cloudwaysapps.com/api/listas/1/products HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDc2YTZlYmVkZjYyZDJjNzkxNTExOTYzNDYyNmNkNjZiMmYzYWJjYzc0YThhNjIxNGYxNzdhMjhiYWEyY2EyN2VhNzQ1NGMzZTc1MjIxMjYiLCJpYXQiOjE2MDU4Mjg4MTgsIm5iZiI6MTYwNTgyODgxOCwiZXhwIjoxNjM3MzY0ODE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.S5k70sTEgt2RANiBTjRNm8_MZ0L7bu03jcqdqufmo_bJeLSCVakRvDnON3lYzCzD4pMCpiYShLh4ZPwPI2-r-7rt02_ntBJsFfpeJlhn9E_d6Mp0Nkfu9ap1WKOfIXpwa6b94geFTtqX-Kp4ZcEXwnrn1Kq0o287aixodR-Qfl5-BfzSflJrbUMMqRHIiBgef4drk8_8jZnu0CfNDcSYFGoUgjIYnKVlO8IzmSIgnXVgCETy5-WXhCQcmobjq8Pb2hJWcj8s6dOvawqygamIjOMB3k4w8-pMNhwtOfnJQTMJ2WDAMp-Vwyq-7rmnrDMnQ6c32XKOf5_8C_xXpPvcQ2oyasw6X-OcLw815XlAylMR2lbrTHEDUrvkxyGtiE87SzeKhaV0THj_PuRJt-wlgnmxkH5hi70fSApGqUSZoDbsCXTVD0tJRvsRH7WGbeKKuCQ6SC2RIVs5lUWu3euA2-qQlmB-iBmrVIFj4pNOFCzY-SswqlH7am0PaynDFIhNJTIap1yhF_LpBqNtQbT3yWBs55nlNLGd3nQlDBh5giCGXpAKhCNO4cpfLghmAk7Iarjkii0LBUmebTZF84w9MXGtOsn-9eyS9HiUIryhSB-X-XDdkPxHoRhjNmwRBX-rwWacgpEumMU_5NwAdsGQpRf0YAx8Tls7SY-a-_56Eo4
Content-type: application/json
Accept: application/json

### Criar Produto em uma lista
POST http://phplaravel-299923-1600849.cloudwaysapps.com/api/listas/1/products HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDc2YTZlYmVkZjYyZDJjNzkxNTExOTYzNDYyNmNkNjZiMmYzYWJjYzc0YThhNjIxNGYxNzdhMjhiYWEyY2EyN2VhNzQ1NGMzZTc1MjIxMjYiLCJpYXQiOjE2MDU4Mjg4MTgsIm5iZiI6MTYwNTgyODgxOCwiZXhwIjoxNjM3MzY0ODE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.S5k70sTEgt2RANiBTjRNm8_MZ0L7bu03jcqdqufmo_bJeLSCVakRvDnON3lYzCzD4pMCpiYShLh4ZPwPI2-r-7rt02_ntBJsFfpeJlhn9E_d6Mp0Nkfu9ap1WKOfIXpwa6b94geFTtqX-Kp4ZcEXwnrn1Kq0o287aixodR-Qfl5-BfzSflJrbUMMqRHIiBgef4drk8_8jZnu0CfNDcSYFGoUgjIYnKVlO8IzmSIgnXVgCETy5-WXhCQcmobjq8Pb2hJWcj8s6dOvawqygamIjOMB3k4w8-pMNhwtOfnJQTMJ2WDAMp-Vwyq-7rmnrDMnQ6c32XKOf5_8C_xXpPvcQ2oyasw6X-OcLw815XlAylMR2lbrTHEDUrvkxyGtiE87SzeKhaV0THj_PuRJt-wlgnmxkH5hi70fSApGqUSZoDbsCXTVD0tJRvsRH7WGbeKKuCQ6SC2RIVs5lUWu3euA2-qQlmB-iBmrVIFj4pNOFCzY-SswqlH7am0PaynDFIhNJTIap1yhF_LpBqNtQbT3yWBs55nlNLGd3nQlDBh5giCGXpAKhCNO4cpfLghmAk7Iarjkii0LBUmebTZF84w9MXGtOsn-9eyS9HiUIryhSB-X-XDdkPxHoRhjNmwRBX-rwWacgpEumMU_5NwAdsGQpRf0YAx8Tls7SY-a-_56Eo4
Content-type: application/json
Accept: application/json

{
    "title": "produto criando.",
    "quantity": 2,
    "value": 10.20
}

### Alterar Produto em uma lista
PUT http://phplaravel-299923-1600849.cloudwaysapps.com/api/listas/1/products/32 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDc2YTZlYmVkZjYyZDJjNzkxNTExOTYzNDYyNmNkNjZiMmYzYWJjYzc0YThhNjIxNGYxNzdhMjhiYWEyY2EyN2VhNzQ1NGMzZTc1MjIxMjYiLCJpYXQiOjE2MDU4Mjg4MTgsIm5iZiI6MTYwNTgyODgxOCwiZXhwIjoxNjM3MzY0ODE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.S5k70sTEgt2RANiBTjRNm8_MZ0L7bu03jcqdqufmo_bJeLSCVakRvDnON3lYzCzD4pMCpiYShLh4ZPwPI2-r-7rt02_ntBJsFfpeJlhn9E_d6Mp0Nkfu9ap1WKOfIXpwa6b94geFTtqX-Kp4ZcEXwnrn1Kq0o287aixodR-Qfl5-BfzSflJrbUMMqRHIiBgef4drk8_8jZnu0CfNDcSYFGoUgjIYnKVlO8IzmSIgnXVgCETy5-WXhCQcmobjq8Pb2hJWcj8s6dOvawqygamIjOMB3k4w8-pMNhwtOfnJQTMJ2WDAMp-Vwyq-7rmnrDMnQ6c32XKOf5_8C_xXpPvcQ2oyasw6X-OcLw815XlAylMR2lbrTHEDUrvkxyGtiE87SzeKhaV0THj_PuRJt-wlgnmxkH5hi70fSApGqUSZoDbsCXTVD0tJRvsRH7WGbeKKuCQ6SC2RIVs5lUWu3euA2-qQlmB-iBmrVIFj4pNOFCzY-SswqlH7am0PaynDFIhNJTIap1yhF_LpBqNtQbT3yWBs55nlNLGd3nQlDBh5giCGXpAKhCNO4cpfLghmAk7Iarjkii0LBUmebTZF84w9MXGtOsn-9eyS9HiUIryhSB-X-XDdkPxHoRhjNmwRBX-rwWacgpEumMU_5NwAdsGQpRf0YAx8Tls7SY-a-_56Eo4
Content-type: application/json
Accept: application/json

{
    "title": "produto renomeado.",
    "quantity": 3,
    "value": 10.30
}

### Remover Produto em uma lista
DELETE http://phplaravel-299923-1600849.cloudwaysapps.com/api/listas/1/products/32 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDc2YTZlYmVkZjYyZDJjNzkxNTExOTYzNDYyNmNkNjZiMmYzYWJjYzc0YThhNjIxNGYxNzdhMjhiYWEyY2EyN2VhNzQ1NGMzZTc1MjIxMjYiLCJpYXQiOjE2MDU4Mjg4MTgsIm5iZiI6MTYwNTgyODgxOCwiZXhwIjoxNjM3MzY0ODE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.S5k70sTEgt2RANiBTjRNm8_MZ0L7bu03jcqdqufmo_bJeLSCVakRvDnON3lYzCzD4pMCpiYShLh4ZPwPI2-r-7rt02_ntBJsFfpeJlhn9E_d6Mp0Nkfu9ap1WKOfIXpwa6b94geFTtqX-Kp4ZcEXwnrn1Kq0o287aixodR-Qfl5-BfzSflJrbUMMqRHIiBgef4drk8_8jZnu0CfNDcSYFGoUgjIYnKVlO8IzmSIgnXVgCETy5-WXhCQcmobjq8Pb2hJWcj8s6dOvawqygamIjOMB3k4w8-pMNhwtOfnJQTMJ2WDAMp-Vwyq-7rmnrDMnQ6c32XKOf5_8C_xXpPvcQ2oyasw6X-OcLw815XlAylMR2lbrTHEDUrvkxyGtiE87SzeKhaV0THj_PuRJt-wlgnmxkH5hi70fSApGqUSZoDbsCXTVD0tJRvsRH7WGbeKKuCQ6SC2RIVs5lUWu3euA2-qQlmB-iBmrVIFj4pNOFCzY-SswqlH7am0PaynDFIhNJTIap1yhF_LpBqNtQbT3yWBs55nlNLGd3nQlDBh5giCGXpAKhCNO4cpfLghmAk7Iarjkii0LBUmebTZF84w9MXGtOsn-9eyS9HiUIryhSB-X-XDdkPxHoRhjNmwRBX-rwWacgpEumMU_5NwAdsGQpRf0YAx8Tls7SY-a-_56Eo4
Content-type: application/json
Accept: application/json
